env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project:
    - "./tsconfig.json"
    - "./packages/*/tsconfig.json"
    - "./api/*/tsconfig.json"
    - "./registryFlow/*/tsconfig.json"
    - "./badgesFlow/*/tsconfig.json"
plugins:
  - "@typescript-eslint"
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
