service: lefthoek-prototype-oauth
frameworkVersion: "2"
variablesResolutionMode: "20210326"
useDotenv: true
plugins:
  - serverless-plugin-monorepo
custom:
  parameter_prefix: lefthoek-prototypes
  datalake_bucket: ${ssm:/${self:custom.parameter_prefix}/datalake/bucket}
  role: ${ssm:/${self:custom.parameter_prefix}/datalake/role}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role: ${self:custom.role}
  region: eu-west-1

functions:
  slack:
    handler: dist/index.slack
    events:
      - httpApi:
          path: /integrations/slack
          method: get
    environment:
      DATALAKE_BUCKET: ${self:custom.datalake_bucket}
      SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
