service: lefthoek-prototype-oauth
frameworkVersion: "2"
plugins:
  - serverless-plugin-monorepo

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1

functions:
  slack:
    handler: dist/index.slack
    events:
      - httpApi:
          path: /integrations/slack
          method: get
    environment:
      SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
